# Dependencies
markdown:         redcarpet

# Permalinks
permalink:        /:title/

# Setup
title:            anderskristo
tagline:          "I make web apps, music lover. <br /> Arsenal enthusiast."
masthead:         default.png
url:              http://anderskristo.me
paginate:         8
baseurl:          /
author:
  name:           Anders Kristoffersson
  url:            http://anderskristo.me
  email:          anderskristo@gmail.com

excerpt_separator: <!--more-->

image_dir: "/public/images/"

# Custom vars
version:          0.1.0
github:
  repo:           https://github.com/anderskristo/anderskristo.github.io

# Excerpt length in words.
excerpt_length: 20
